### ISSUE TITLE
how to provide SSL details with KSQLDB URL

### ISSUE THREAD

**Issue by ansarizakir** [rmoff/vsc-ksql#14]
Hi,

We are using Confluent 6.1 and want to provide separate UI for KSQLDB for users. This tool looks good but how to provide SSL details, I can see only URL which is KSQLDB URL needs to provide . Can you please guide how and where to provide SSL details with KSQLDB URL.

**Comment by rmoff** [comment]
Duplicate of #12

**Comment by rmoff** [comment]
This is not implemented in the plugin currently.
